# notifier.py - Google Drive Upload and Email Notification Module
# =================================================================

import json
import os
import smtplib
from datetime import datetime
from email import encoders
from email.mime.base import MIMEBase
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import Optional

from google.oauth2 import service_account
from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload

from utils import logger


def load_google_credentials() -> Optional[service_account.Credentials]:
    """
    Loads Google Drive Service Account Credentials from either a JSON file path
    or a raw JSON string environment variable.
    """
    scopes = ['https://www.googleapis.com/auth/drive']
    
    # 1. Try file path first if provided
    creds_path = os.getenv("GOOGLE_CREDENTIALS_FILE")
    if creds_path and os.path.exists(creds_path):
        try:
            return service_account.Credentials.from_service_account_file(creds_path, scopes=scopes)
        except Exception as e:
            logger.warning(f"Failed to load credentials from file '{creds_path}': {e}")

    # 2. Try raw JSON string
    creds_json = os.getenv("GOOGLE_CREDENTIALS_JSON")
    if creds_json:
        try:
            creds_dict = json.loads(creds_json)
            return service_account.Credentials.from_service_account_info(creds_dict, scopes=scopes)
        except Exception as e:
            logger.warning(f"Failed to parse GOOGLE_CREDENTIALS_JSON: {e}")
            
    return None


def upload_to_drive(filename: str) -> Optional[str]:
    """
    Upload a generated document to specified Google Drive folder.
    """
    folder_id = os.getenv("DRIVE_FOLDER_ID")
    if not folder_id:
        logger.warning("Skipping Drive upload: DRIVE_FOLDER_ID not configured")
        return None

    creds = load_google_credentials()
    if not creds:
        logger.warning("Skipping Drive upload: Valid Google Service Account credentials missing")
        return None

    logger.info(f"☁️ Uploading to Google Drive: {filename}")
    try:
        service = build('drive', 'v3', credentials=creds)
        file_metadata = {'name': filename, 'parents': [folder_id]}
        media = MediaFileUpload(
            filename,
            mimetype='application/vnd.openxmlformats-officedocument.wordprocessingml.document',
            resumable=True
        )
        
        file = service.files().create(body=file_metadata, media_body=media, fields='id').execute()
        file_id = file.get('id')
        logger.info(f"✅ Drive Upload Success! ID={file_id}")
        return file_id
    except Exception as e:
        logger.error(f"Drive upload failed: {e}")
        return None


def send_email(filename: str, recipient: Optional[str] = None) -> bool:
    """
    Send daily report as email attachment via SMTP.
    """
    sender_email = os.getenv("EMAIL_SENDER")
    sender_password = os.getenv("EMAIL_PASSWORD")
    
    if not sender_email or not sender_password:
        logger.warning("Skipping email notification: EMAIL_SENDER or EMAIL_PASSWORD missing")
        return False

    target_recipient = recipient or sender_email
    logger.info(f"📧 Sending email report to: {target_recipient}")
    
    try:
        msg = MIMEMultipart()
        msg['From'] = sender_email
        msg['To'] = target_recipient
        msg['Subject'] = f"Rice News Report: {datetime.now().strftime('%Y-%m-%d')}"
        
        body = "Attached is the Daily Rice News Report generated by the automated script."
        msg.attach(MIMEText(body, 'plain'))

        with open(filename, "rb") as attachment:
            part = MIMEBase("application", "octet-stream")
            part.set_payload(attachment.read())
            
        encoders.encode_base64(part)
        part.add_header("Content-Disposition", f"attachment; filename={filename}")
        msg.attach(part)

        smtp_server = os.getenv("SMTP_SERVER", "smtp.gmail.com")
        smtp_port = int(os.getenv("SMTP_PORT", 587))

        with smtplib.SMTP(smtp_server, smtp_port) as server:
            server.starttls()
            server.login(sender_email, sender_password)
            server.sendmail(sender_email, target_recipient, msg.as_string())
            
        logger.info("✅ Email sent successfully.")
        return True
    except Exception as e:
        logger.error(f"Email delivery failed: {e}")
        return False
